-- =====================================================
-- Table: <table_name>
-- Purpose: <description>
-- Created: <date>
-- =====================================================

-- =====================================================
-- Table: <table_name>
-- Purpose: <description>
-- Created: <date>
-- =====================================================

CREATE TABLE <table_name> (

    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Audit Fields
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    updated_by UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL

    -- Business Fields
    -- (replace these with your actual columns)

);

-- =====================================================
-- Security
-- =====================================================

-- Enable Row Level Security (RLS)
ALTER TABLE public.<table_name> ENABLE ROW LEVEL SECURITY;

-- Optional (Stricter):
-- ALTER TABLE public.<table_name> FORCE ROW LEVEL SECURITY;

-- =====================================================
-- Trigger: Audit Fields
-- Purpose: Protect created_* and auto-update updated_*
-- =====================================================

DROP TRIGGER IF EXISTS <table_name>_audit ON public.<table_name>;

CREATE TRIGGER <table_name>_audit
BEFORE INSERT OR UPDATE ON public.<table_name>
FOR EACH ROW
EXECUTE FUNCTION set_audit_fields();