


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."set_audit_fields"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := now();
        NEW.updated_at := now();

        IF auth.uid() IS NOT NULL THEN
            NEW.created_by := auth.uid();
            NEW.updated_by := auth.uid();
        ELSE
            NEW.created_by := 'f1d8fd7b-6f77-4603-9443-f64dcf6d9fe4';
            NEW.updated_by := 'f1d8fd7b-6f77-4603-9443-f64dcf6d9fe4';
        END IF;

    ELSIF TG_OP = 'UPDATE' THEN
        -- Preserve creation metadata
        NEW.created_at := OLD.created_at;
        NEW.created_by := OLD.created_by;

        -- Always update modification metadata
        NEW.updated_at := now();

        IF auth.uid() IS NOT NULL THEN
            NEW.updated_by := auth.uid();
        ELSE
            NEW.updated_by := 'f1d8fd7b-6f77-4603-9443-f64dcf6d9fe4';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."set_audit_fields"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."organization_roles" (
    "id" bigint NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid" NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" character varying NOT NULL,
    "qb_id" bigint,
    "organization_id" bigint NOT NULL
);


ALTER TABLE "public"."organization_roles" OWNER TO "postgres";


ALTER TABLE "public"."organization_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organization_roles_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organization_user_roles" (
    "id" bigint NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid" NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "organization_user_id" bigint NOT NULL,
    "organization_role_id" bigint NOT NULL,
    "bio" character varying
);


ALTER TABLE "public"."organization_user_roles" OWNER TO "postgres";


ALTER TABLE "public"."organization_user_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organization_user_roles_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organization_users" (
    "id" bigint NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid" NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "organization_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."organization_users" OWNER TO "postgres";


ALTER TABLE "public"."organization_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organization_users_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid" NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "name" character varying NOT NULL,
    "qb_id" bigint,
    "active" boolean NOT NULL
);


ALTER TABLE "public"."organizations" OWNER TO "postgres";


ALTER TABLE "public"."organizations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organizations_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid",
    "updated_at" timestamp with time zone NOT NULL,
    "display_name" "text" NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."organizations_view" WITH ("security_invoker"='true') AS
 SELECT "t"."id",
    "t"."name",
    "t"."qb_id",
    "t"."active",
    "to_char"("t"."created_at", 'YYYY-MM-DD HH24:MI'::"text") AS "created_at",
    "to_char"("t"."updated_at", 'YYYY-MM-DD HH24:MI'::"text") AS "updated_at",
    "cb"."display_name" AS "created_by",
    "ub"."display_name" AS "updated_by"
   FROM (("public"."organizations" "t"
     LEFT JOIN "public"."users" "cb" ON (("t"."created_by" = "cb"."id")))
     LEFT JOIN "public"."users" "ub" ON (("t"."updated_by" = "ub"."id")));


ALTER VIEW "public"."organizations_view" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sync_events" (
    "id" bigint NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" "uuid" NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "entity" "text" NOT NULL,
    "dry_run" boolean DEFAULT false NOT NULL,
    "received_count" integer NOT NULL,
    "valid_count" integer NOT NULL,
    "failed_count" integer NOT NULL,
    "status" "text" NOT NULL,
    "errors" "jsonb",
    "meta" "jsonb"
);


ALTER TABLE "public"."sync_events" OWNER TO "postgres";


ALTER TABLE "public"."sync_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sync_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."organization_roles"
    ADD CONSTRAINT "organization_roles_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organization_roles"
    ADD CONSTRAINT "organization_roles_qb_id_key" UNIQUE ("qb_id");



ALTER TABLE ONLY "public"."organization_user_roles"
    ADD CONSTRAINT "organization_user_roles_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organization_users"
    ADD CONSTRAINT "organization_users_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_qb_id_key" UNIQUE ("qb_id");



ALTER TABLE ONLY "public"."sync_events"
    ADD CONSTRAINT "sync_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey1" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "organization_roles_audit" BEFORE INSERT OR UPDATE ON "public"."organization_roles" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



CREATE OR REPLACE TRIGGER "organization_user_roles_audit" BEFORE INSERT OR UPDATE ON "public"."organization_user_roles" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



CREATE OR REPLACE TRIGGER "organization_users_audit" BEFORE INSERT OR UPDATE ON "public"."organization_users" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



CREATE OR REPLACE TRIGGER "organizations_audit" BEFORE INSERT OR UPDATE ON "public"."organizations" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



CREATE OR REPLACE TRIGGER "sync_events_audit" BEFORE INSERT OR UPDATE ON "public"."sync_events" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



CREATE OR REPLACE TRIGGER "users_audit" BEFORE INSERT OR UPDATE ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."set_audit_fields"();



ALTER TABLE ONLY "public"."organization_roles"
    ADD CONSTRAINT "organization_roles_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_roles"
    ADD CONSTRAINT "organization_roles_organization_id_fkey1" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."organization_roles"
    ADD CONSTRAINT "organization_roles_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_user_roles"
    ADD CONSTRAINT "organization_user_roles_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_user_roles"
    ADD CONSTRAINT "organization_user_roles_organization_role_id_fkey" FOREIGN KEY ("organization_role_id") REFERENCES "public"."organization_roles"("id");



ALTER TABLE ONLY "public"."organization_user_roles"
    ADD CONSTRAINT "organization_user_roles_organization_user_id_fkey" FOREIGN KEY ("organization_user_id") REFERENCES "public"."organization_users"("id");



ALTER TABLE ONLY "public"."organization_user_roles"
    ADD CONSTRAINT "organization_user_roles_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_users"
    ADD CONSTRAINT "organization_users_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_users"
    ADD CONSTRAINT "organization_users_organization_id_fkey1" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."organization_users"
    ADD CONSTRAINT "organization_users_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organization_users"
    ADD CONSTRAINT "organization_users_user_id_fkey1" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey1" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");



ALTER TABLE "public"."organization_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."organization_user_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."organization_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sync_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."set_audit_fields"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_audit_fields"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_audit_fields"() TO "service_role";


















GRANT ALL ON TABLE "public"."organization_roles" TO "anon";
GRANT ALL ON TABLE "public"."organization_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."organization_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organization_roles_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."organization_roles_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organization_roles_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."organization_user_roles" TO "anon";
GRANT ALL ON TABLE "public"."organization_user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."organization_user_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organization_user_roles_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."organization_user_roles_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organization_user_roles_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."organization_users" TO "anon";
GRANT ALL ON TABLE "public"."organization_users" TO "authenticated";
GRANT ALL ON TABLE "public"."organization_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organization_users_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."organization_users_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organization_users_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organizations_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."organizations_view" TO "anon";
GRANT ALL ON TABLE "public"."organizations_view" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations_view" TO "service_role";



GRANT ALL ON TABLE "public"."sync_events" TO "anon";
GRANT ALL ON TABLE "public"."sync_events" TO "authenticated";
GRANT ALL ON TABLE "public"."sync_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sync_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sync_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sync_events_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


